version: "3"   # docker compose version
services:      # can have multiple container
 node-app:     # container name
  build:
    context: . # context is basically location of dockerfile
    args:
      NODE_ENV: production
  environment:         # environment variables for port define
    - NODE_ENV = production
  command: node index.js   # for running index.js file
