version: "3"   # docker compose version
services:      # can have multiple container
 node-app:     # container name
  build:
    context: . # context is basically location of dockerfile
    args:
      NODE_ENV: development
  volumes:     # %cd% or ${pwd}, you have seen in previous
    - ./:/app
    - /app/node_modules # using container files node_modules, not project node_modules,you have seen in previous file
  environment:         # environment variables for port define
    - NODE_ENV = development
    - MONGO_INITDB_ROOT_USERNAME=sunil
    - MONGO_INITDB_ROOT_PASSWORD=mypassword
  command: npm run dev   # for running index.js file


 mongo:
  environment:
    - MONGO_INITDB_ROOT_USERNAME=sunil
    - MONGO_INITDB_ROOT_PASSWORD=mypassword
